### ISSUE TITLE
Doesn't work. I want my money back

### ISSUE THREAD

**Issue by Herbert-Haase** [Atomarverseucht/minesweeper#38]
Tested "java -jar ./minesweeper-assembly-1.2.1.jar" and got this error message after putting in the count of bombs.
I don't think the count of bombs and the other numbers I put in matter, since after several tries with different numbers I always get the same error message.

Tried it on arch linux using Open-JDK 21.
Host: D3400-A1
OS: EndeavourOS Linux x86_69
WM: i3
CPU: Intel i5-6400 (4) @ 3.300GHz 
GPU: NVIDIA GeForce GTX 1650 
Memory: 15882MiB

I have not payed, but I want my money back. 3000 € would be fine. 
Or at least put in which dependencies we should use.
"
Please enter the count of bombs. It must be between 1 and 135
3
Exception in thread "main" java.lang.UnsupportedClassVersionError: javafx/scene/input/KeyCode has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at de.htwg.winesmeeper.Controller.ImplSysCommands.UndoCmd$.<clinit>(UndoCmd.scala:11)
	at de.htwg.winesmeeper.Controller.ImplSysCommands.SaveCmd$.<clinit>(SaveCmd.scala:10)
	at de.htwg.winesmeeper.Controller.ImplSysCommands.RedoCmd$.<clinit>(RedoCmd.scala:12)
	at de.htwg.winesmeeper.Controller.ImplSysCommands.QuitCmd$.<clinit>(QuitCmd.scala:9)
	at de.htwg.winesmeeper.Controller.ImplSysCommands.LoadCmd$.<clinit>(LoadCmd.scala:16)
	at de.htwg.winesmeeper.Controller.ImplSysCommands.HelpCmd$.<clinit>(HelpCmd.scala:9)
	at de.htwg.winesmeeper.Controller.ImplSysCommands.SysCommandManager$.<clinit>(SysCmdManager.scala:9)
	at de.htwg.winesmeeper.Config$.<clinit>(Config.scala:18)
	at de.htwg.winesmeeper.Model.BoardImplementation.Board$.$anonfun$1(Board.scala:66)
	at scala.collection.StrictOptimizedSeqFactory.fill(Factory.scala:330)
	at scala.collection.StrictOptimizedSeqFactory.fill$(Factory.scala:325)
	at scala.collection.immutable.Vector$.fill(Vector.scala:34)
	at scala.collection.immutable.Vector$.fill(Vector.scala:34)
	at scala.collection.IterableFactory.$anonfun$fill$1(Factory.scala:161)
	at scala.collection.StrictOptimizedSeqFactory.fill(Factory.scala:330)
	at scala.collection.StrictOptimizedSeqFactory.fill$(Factory.scala:325)
	at scala.collection.immutable.Vector$.fill(Vector.scala:34)
	at scala.collection.immutable.Vector$.fill(Vector.scala:34)
	at scala.collection.IterableFactory.fill(Factory.scala:161)
	at scala.collection.IterableFactory.fill$(Factory.scala:161)
	at scala.collection.immutable.Vector$.fill(Vector.scala:34)
	at de.htwg.winesmeeper.Model.BoardImplementation.Board$.apply(Board.scala:66)
	at de.htwg.winesmeeper.Main$package$.start(Main.scala:15)
	at de.htwg.winesmeeper.start.main(Main.scala:11)
"

**Comment by Atomarverseucht** [comment]
With the new version 2.1.0, it should be fixed. So i hope your issue is fixed. Thanks for your bug report!

**Comment by Herbert-Haase** [comment]
Sorry, still does not work.
"
└── ❯ java -jar ./minesweeper-assembly-2.1.0.jar
##########
##########
##########
##########
##########
##########
##########
##########
##########
##########

Jan 20, 2026 12:53:59 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6d27a029'
Exception in thread "JavaFX Application Thread" java.lang.StackOverflowError
	at java.base/java.util.Arrays.copyOf(Arrays.java:3482)
	at scala.collection.immutable.VectorBuilder.result(Vector.scala:2030)
	at scala.collection.immutable.VectorBuilder.result(Vector.scala:1397)
	at scala.collection.immutable.Range.map(Range.scala:60)
	at de.htwg.winesmeeper.Model.ImplBoard.Board.getBombNeighbour$$anonfun$1(Board.scala:16)
	at de.htwg.winesmeeper.Model.ImplBoard.Board.getBombNeighbour$$anonfun$adapted$1(Board.scala:15)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.immutable.Range.flatMap(Range.scala:60)
	at de.htwg.winesmeeper.Model.ImplBoard.Board.getBombNeighbour(Board.scala:15)
"
action taken:
- clicked generate
- focus new window and enter 100 for X-size, 100 for Y-Size, and 1 for Bomb count
- click save

window for entering sizes closes and nothing happens in gui.

**Comment by Atomarverseucht** [comment]
The positive is, we have a new bug, but we are making progress.
